export const style = {
    MODAL_STYLE: {
        position: "fixed",
        top: "0%",
        left: "0%",
        width: "100%",
        height: "100vh",
        backgroundColor: "rgba(0, 0, 0,.6)",
        fontSize: "1.8em",
    },
    OVERLAY_STYLE: {
        position: "fixed",
        top: "50%",
        left: "50%",
        transform: "translate(-50%,-50%)",
        height: "70%",
        width: "80%",
        zIndex: 3,
        textAlign: "center",
        backgroundColor: "#fff",
    },

    RED_CROSS_STYLE: {
        height: "50px",
        width: "50px",
        borderRadius: "50%",
        backgroundColor: "red",
        zIndex: "10",
        cursor: "pointer",
    },

    CONTENT_CONTAINER_STYLE: {
        position: "relative",
        overflowX: "hidden",
        height: "100%",
        width: "100%",
        zIndex: "-1",
    },
    ANCHOR_STYLE: {
        display: "block",
    },
    P_STYLE: {
        margin: "30px 0px 30px 0px",
    },
    PROJECT_CONTAINER_STYLE: {
        position: "relative",
        left: "50%",
        transform: "translate(-50%)",
        margin: "40px 0px 50px 0px",
        height: "230px",
        width: "250px",
        boxShadow: "-2px -1px 52px 10px rgba(0,0,0,0.83)",
    },
    PROJ_BUTTON_STYLE: {
        position: "absolute",
        borderRadius: "50%",
        height: "70px",
        width: "70px",
        textAlign: "center",
        top: "64%",
        left: "40%",
        cursor: "pointer",
        outline: "inherit",
        border: "none",
        fontSize: "17px",
        color: "#fff",
        background: "rgb(10, 152, 5)",
        boxShadow: " inset 0px 0px  15px 0px rgb(0, 12, 5)",
    },
    WEB_BUTTON_STYLE: {
        position: "absolute",
        borderRadius: "8%",
        height: "55px",
        width: "80px",
        textAlign: "center",
        top: "4%",
        left: "5%",
        cursor: "pointer",
        outline: "inherit",
        border: "none",
        fontSize: "16px",
        background: "rgb(70, 188, 305)",
        boxShadow: " inset 0px 0px  10px 0px  rgb(12, 20, 7)",
    },
    CV_BUTTON_STYLE: {
        display: "block",
        position: "relative",
        borderRadius: "8%",
        height: "55px",
        width: "80px",
        textAlign: "center",
        left: "50%",
        transform: "translate(-50%)",
        marginBottom: "50px",
        cursor: "pointer",
        outline: "inherit",
        border: "none",
        marginTop: "50px",
        textDecoration: "none",
        fontSize: "16px",
        background: "rgb(245, 210, 9)",
        boxShadow: " inset 0px 0px  10px 0px rgb(15, 0, 9)",
    },
    IMG_STYLE: {
        height: "230px",
        width: "250px",
    },
    HR_CONTACT_STYLE: {
        position: "relative",
        width: "25%",
        left: "50%",
        transform: "translate(-50%)",
        margin: "20px 0px 20px 0px",
    },
    P_CONTACT: {
        wordBreak: "break-word",
        paddingRight: "5px",
    },
    SPAN_CONTACT_STYLE: {fontWeight: "bold"},
    PARA_STYLE: {paddingLeft: "10%", paddingRight: "10%"},
    PARA_CONTENT_STYLE: {
        position: "relative",
        backgroundColor: " rgb(219, 221, 119)",
        width: "100%",
        marginTop: "50px",
        paddingTop: "50px",
        paddingBottom: "50px",
        zIndex: "-1",
    },
    P_CONTENT_STYLE: {
        paddingLeft: "20px",
        paddingRight: "20px",
    },
};
